[package]
name = "crowbook"
version = "0.13.0"
authors = ["Elisabeth Henry <liz.henry@ouvaton.org>"]
description = "Render a Markdown book in HTML, PDF or Epub"
repository = "https://github.com/lise-henry/crowbook"
documentation = "https://docs.rs/crowbook/"
readme = "README.md"
keywords = ["markdown", "book"]
categories = ["command-line-utilities", "text-processing"]
license = "LGPL-2.1+"
publish = true
build = "build.rs"

exclude = [
    "docs/*",
    "img/*",
    "config.book",
    "book_example/*",
    "ci/*",
    ".travis.yml",
    "appveyor.yml",
]

[badges]
travis-ci = { repository = "lise-henry/crowbook" }
appveyor = { repository = "lise-henry/crowbook" }

[lib]
name = "crowbook"
path = "src/lib/lib.rs"
doctest = false

[[bin]]
name = "crowbook"
path = "src/bin/main.rs"
doc = false

[features]
default = ["clap", "proofread", "syntect"]
proofread = ["caribon", "hyper", "url"]

[build-dependencies]
crowbook-intl = "0.2"

[dependencies]
mime_guess = "1"
pulldown-cmark = "0.0.15"
yaml-rust = "0.3"
mustache = "0.8"
uuid = { version = "0.5", features = ["v4"] }
walkdir = "1.0"
rustc-serialize = "0.3"
rayon = "0.8"
crowbook-text-processing = "^0.2.6"
lazy_static = "0.2.1"
term = "0.4"
crowbook-intl-runtime = "0.1"
numerals = "0.1"
epub-builder = "0.2"
caribon = { version = "0.8", optional = true }
clap = { version = "2.19", optional = true }
url =  { version = "1", optional = true }
syntect = { version = "1", optional = true }

[dependencies.hyper]
version = "0.10"
optional = true
default-features = false
