[package]
name = "crowbook"
version = "0.9.1-unreleased"
authors = ["Elisabeth Henry <liz.henry@ouvaton.org>"]
description = "Render a Markdown book in HTML, PDF or Epub"
repository = "https://github.com/lise-henry/crowbook"
documentation = "https://docs.rs/crowbook/"
readme = "README.md"
keywords = ["markdown", "book"]
license = "LGPL-2.1+"
publish = false

exclude = [
    "docs/*",
    "img/*",
    "config.book",
    "book_example/*",
    "ci/*",
    ".travis.yml",
    "appveyor.yml",
]
    
[lib]
name = "crowbook"
path = "src/lib/lib.rs"
doctest = false

[[bin]]
name = "crowbook"
path = "src/bin/main.rs"
doc = false

# [[bin]]
# name = "test_cleaner"
# path = "src/bin/test_cleaner.rs"
# doc = false

[features]
repetitions = ["caribon"]

[dependencies]
mime_guess = "1"
pulldown-cmark = "0.0.8"
yaml-rust = "0.3"
mustache = "0.7"
chrono = "0.2"
uuid = { version = "0.3", features = ["v4"] }
clap = "2"
walkdir = "0.1"
rustc-serialize = "0.3"
crossbeam = "0.2"
caribon = { version = "0.7", optional = true }
