[package]
name = "crowbook"
version = "0.1.0-unreleased"
authors = ["Elisabeth Henry <liz.henry@ouvaton.org>"]
description = "Yet another converter from Markdown file to (HTML, LaTeX, Epub)"
repository = "https://github.com/lise-henry/crowbook"
readme = "README.md"
keywords = ["markdown", "book"]
license = "mit"

[lib]
name = "crowbook"
path = "src/lib/lib.rs"

[[bin]]
name = "crowbook"
path = "src/bin/main.rs"
doc = false

[dependencies]
pulldown-cmark = "0.0.7"
mustache = "0.6"
chrono = "0.2"
uuid = "0.1"
clap = "2"