[package]
name = "crowbook"
version = "0.2.0-beta1"
authors = ["Elisabeth Henry <liz.henry@ouvaton.org>"]
description = "Render a book written in Markdown in HTML, PDF or Epub"
repository = "https://github.com/lise-henry/crowbook"
readme = "README.md"
keywords = ["markdown", "book"]
license = "LGPL-2.1+"

[lib]
name = "crowbook"
path = "src/lib/lib.rs"

[[bin]]
name = "crowbook"
path = "src/bin/main.rs"
doc = false

[dependencies]
pulldown-cmark = "0.0.7"
mustache = "0.6"
chrono = "0.2"
uuid = "0.1"
clap = "2"