[package]
name = "crowbook"
version = "0.11.1-pre"
authors = ["Elisabeth Henry <liz.henry@ouvaton.org>"]
description = "Render a Markdown book in HTML, PDF or Epub"
repository = "https://github.com/lise-henry/crowbook"
documentation = "https://docs.rs/crowbook/"
readme = "README.md"
keywords = ["markdown", "book"]
license = "LGPL-2.1+"
publish = false
build = "build.rs"

exclude = [
    "docs/*",
    "img/*",
    "config.book",
    "book_example/*",
    "ci/*",
    ".travis.yml",
    "appveyor.yml",
]
    
[lib]
name = "crowbook"
path = "src/lib/lib.rs"
doctest = false

[[bin]]
name = "crowbook"
path = "src/bin/main.rs"
doc = false

[features]
default = ["clap", "proofread"]
proofread = ["caribon", "hyper", "url"]

[build-dependencies]
crowbook-intl = "0.2"

[dependencies]
mime_guess = "1"
pulldown-cmark = "0.0.8"
yaml-rust = "0.3"
mustache = "0.8"
chrono = "0.2"
uuid = { version = "0.3", features = ["v4"] }
walkdir = "1.0"
rustc-serialize = "0.3"
crossbeam = "0.2"
crowbook-text-processing = "^0.2.2"
lazy_static = "0.2.1"
term = "0.4"
crowbook-intl-runtime = "0.1"
caribon = { version = "0.7", optional = true }
clap = { version = "2", optional = true }
url =  { version = "1", optional = true }
numerals = "0.1"
epub = { git = "https://github.com/lise-henry/epub.git" }

[dependencies.hyper]
version = "0.9"
optional = true
default-features = false
