[package]
name = "crowbook"
version = "0.1.0"
authors = ["Elisabeth Henry <liz.henry@ouvaton.org>"]

[lib]
name = "crowbook"
path = "src/lib/lib.rs"

[[bin]]
name = "crowbook"
path = "src/bin/main.rs"
doc = false

[dependencies]
pulldown-cmark = "0.0.7"
mustache = "0.6"
rustc-serialize = "0.3"